### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by nerkn** [warren-bank/node-rtsp-relay#1]
I had a little trouble sending from  ffmpeg and reading from vlc. 

For ffmpeg I made this command, I suggest you to add as example, since path is important

ffmpeg   -re   -f alsa -ac 2 -i hw:0  -f v4l2  -i /dev/video3  -vcodec libx264 -pix_fmt yuv420p  -preset veryfast   -f rtsp  rtsp://SERVERIP:5554/PATH

But I cant watch from vlc, where I used "rtsp://SERVERIP:6554/robos"

> 
>   rtsp-relay:2:ConsumerServer ::ffff:46.155.146.18:56225 request: OPTIONS +198ms
>   rtsp-relay:2:ConsumerServer ::ffff:46.155.146.18:55688 request: OPTIONS +13s
>   rtsp-relay:2:ConsumerServer ::ffff:46.155.146.18:55688 request: DESCRIBE +81ms
>   rtsp-relay:2:ConsumerServer ::ffff:46.155.146.18:55688 request: SETUP +87ms
>   rtsp-relay:2:ClientWrapper 6414420869107103751991741278221246126125243 - constructed +1ms
>   rtsp-relay:2:Mounts 497 rtp ports remaining +4ms
>   rtsp-relay:2:ClientWrapper 6414420869107103751991741278221246126125243 new client 5145105554423064113128248282111512541335 +0ms
>   rtsp-relay:2:Client ::ffff:46.155.146.18:55688 Client set up for path /robos, local ports (1004:1005) remote ports (52054:52055) +1ms
>   rtsp-relay:2:ConsumerServer ::ffff:46.155.146.18:55688 request: SETUP +66ms
>   rtsp-relay:2:Mounts 496 rtp ports remaining +1ms
>   rtsp-relay:2:ClientWrapper 6414420869107103751991741278221246126125243 new client 1149441264972190161742531891966697175 +0ms
>   rtsp-relay:2:Client ::ffff:46.155.146.18:55688 Client set up for path /robos, local ports (1006:1007) remote ports (42586:42587) +1ms
>   rtsp-relay:2:ConsumerServer ::ffff:46.155.146.18:55688 request: PLAY +107ms
>   rtsp-relay:2:ConsumerServer 6414420869107103751991741278221246126125243 calling play +0ms
>   rtsp-relay:2:ConsumerServer ::ffff:46.155.146.18:55688 request: TEARDOWN +11s
>   rtsp-relay:2:ConsumerServer ::ffff:46.155.146.18:55688 tearing down client +1ms
>   rtsp-relay:2:Mounts 497 rtp ports remaining +1ms
>   rtsp-relay:2:Mounts 498 rtp ports remaining +1ms
>   rtsp-relay:2:ConsumerServer ClientWrapper 6414420869107103751991741278221246126125243 gone +0ms
>   rtsp-relay:2:ConsumerServer ::ffff:46.155.146.18:55817 request: OPTIONS +46ms
>   rtsp-relay:2:ConsumerServer ::ffff:46.155.146.18:55817 request: DESCRIBE +58ms
>   rtsp-relay:2:ConsumerServer ::ffff:46.155.146.18:55817 request: SETUP +131ms
>   rtsp-relay:2:ConsumerServer ::ffff:46.155.146.18:55817 - we dont support tcp, sending 504: 'rtsp://77.83.202.39:6554/robos/streamid=0' +1ms
>   rtsp-relay:2:ConsumerServer ::ffff:46.155.146.18:55817 request: SETUP +68ms
>   rtsp-relay:2:ConsumerServer ::ffff:46.155.146.18:55817 - we dont support tcp, sending 504: 'rtsp://77.83.202.39:6554/robos/streamid=1' +0ms
> 

node is running under docker where all ports are exposed with " --network host"

**Comment by warren-bank** [comment]
wow, I must be getting old.. I don't even remember writing this repo.

anyway, I glanced over the README.. and see from the error messages in your log that you're hitting the "limitation" it mentions:

> limitations (inherited from rtsp-streaming-server library)
> * doesn't support RTP/RTSP/TCP

You'll want to see whether ffmpeg can stream using the older protocol (using RTP and RTCP ports).
If you find the proper CLI incantation to make it all work, it would be great if you could post an update to this issue (for future reference).

Sorry I couldn't be more help.

**Comment by warren-bank** [comment]
Here's a working example using ffmpeg (for both producer and consumer)..

_important_: order matters

1. start the rtsp relay server
   ```bash
     rtsp-relay -pport 5554 -cport 6554 --log 5 >log.txt 2>&1
   ```
2. start the rtsp producer server (connect to relay at port 5554)
   ```bash
     ffmpeg -re -stream_loop -1 -i test.mp4 -f rtsp -rtsp_transport udp rtsp://127.0.0.1:5554/stream1
   ```
3. start the rtsp consumer client (connect to relay at port 6554)
   ```bash
     ffplay -rtsp_transport udp rtsp://127.0.0.1:6554/stream1
   ```

where:
* a [sample mp4 video](https://file-examples.com/index.php/sample-video-files/sample-mp4-files/) was downloaded to the current directory and named `test.mp4`
* the relay server's verbosity was ramped all the way up and output was logged to a text file named `log.txt`

update:
* tested using VLC as the consumer.. and it works fine

**Comment by warren-bank** [comment]
[here](https://github.com/warren-bank/node-rtsp-relay/tree/master/tests) is a slightly more polished example :smiley:

**Comment by warren-bank** [comment]
circling back to your initial comment, try running this for your producer:

```bash
ffmpeg -re -f alsa -ac 2 -i hw:0 -f v4l2 -i /dev/video3 -c:v mpeg1video -q 15 -pix_fmt yuv420p -preset veryfast -f rtsp -rtsp_transport udp -muxdelay 0.1 rtsp://SERVERIP:5554/PATH
```

**Comment by hnguyen48206** [comment]
I hope that this message still be able to reach you guys at this moment. I have tried running the setup just as you @warren-bank mentioned above sir but when I start the ffplay command, I encountered disconnection right away. After adding the logs options, this is what happened.

![image](https://user-images.githubusercontent.com/28868992/215688560-943a03d5-cc91-4e14-9bbf-43b76623455a.png)

Any help would be much appriciated.

**Comment by warren-bank** [comment]
thoughts/comments:
1. yet again.. "wow, I must be getting old.. I don't even remember writing this repo."
2. I just downloaded the [zip snapshot](https://github.com/warren-bank/node-rtsp-relay/archive/refs/heads/master.zip) for the HEAD of the master branch
   - ran `npm install` in both the project root directory, as well as in `./tests`
   - ran each of the following batch files.. concurrently.. in separate terminals:
     * [./tests/01-ffmpeg/1-rtsp-relay.bat](https://github.com/warren-bank/node-rtsp-relay/blob/master/tests/01-ffmpeg/1-rtsp-relay.bat)
     * [./tests/01-ffmpeg/2-rtsp-producer.bat](https://github.com/warren-bank/node-rtsp-relay/blob/master/tests/01-ffmpeg/2-rtsp-producer.bat)
     * [./tests/01-ffmpeg/3-rtsp-consumer-ffplay.bat](https://github.com/warren-bank/node-rtsp-relay/blob/master/tests/01-ffmpeg/3-rtsp-consumer-ffplay.bat)
3. everything worked exactly as it should
   - Cyndi Lauper was.. is.. and always will be amazing :smiley:
5. looking at the screenshot of the log messages in your terminal..
   - it seems that you were trying to bind to port 1008.. but were unable to do so.
   - was this port already in use at the time of your test?
   - __update__: on linux.. ports &lt; 1024 are protected.. and require root privilege
     * try using a higher port number

**Comment by hnguyen48206** [comment]
Thank you for your timely response sir. Yes, based on the console log, seems like something is wrong with the port 1008 which is where I got lost since I do not purposely using that port. And I have aslo checked the opening ports on the server at that moment, then saw no 1008 port at all.

**Comment by hnguyen48206** [comment]
And this is the command that I have used to start the server: rtsp-relay -pport 5554 -cport 6554 --log-level 3
I have noticed in your message that you mentioned pulling the project and do npm i which I did not follow. I've just install the package globally as being described in README, may that be the reason?

**Comment by warren-bank** [comment]
global install is fine.. i was just testing in a disposable directory

very odd.. `-cport` is the "consumer port".. which your log message indicates is trying to bind to 1008.
off-hand.. no idea why this is happening..

**Comment by warren-bank** [comment]
darnit..
darnit..
ok, I found the problem.. and it's a bug..
completely my fault:

[this](https://github.com/warren-bank/node-rtsp-relay/blob/v1.0.0/bin/rtsp-relay/process_argv.js#L81) defaults `--rtp-low-port` to `1,000`.. but the README says that it should default to `10,000`

I forgot a zero..

I'll fix it now and push an update to npm.
I'll add another quick comment to let you know when you can pull the fix.
Thanks for finding this.. and letting me know about it.

**Comment by hnguyen48206** [comment]
No problem sir. Just give me a ping when it's possible.

**Comment by warren-bank** [comment]
ok.. I just pushed [`v1.0.2`](https://github.com/warren-bank/node-rtsp-relay/releases/tag/v1.0.2) to [npm](https://www.npmjs.com/package/@warren-bank/rtsp-relay).

please let me know if this fixes the problem.. (it should)

**Comment by hnguyen48206** [comment]
@warren-bank awesome as it should be.

Best Regards.
